modLoader = "javafml"
loaderVersion = "[44,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"
logoFile = "logo.png"
logoBlur = false

[[mods]]
modId = "${mod_id}"
updateJSONURL = "https://updates.blamejared.com/get?n=${mod_id}&gv=${minecraft_version}"
version = "${file.jarVersion}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
credits = "This project is made possible with Patreon support from players like you. Thank you! ${mod_supporters}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
itemIcon = "botanypots:terracotta_botany_pot"

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "bookshelf"
mandatory = true
versionRange = "[17,)"
ordering = "NONE"
side = "BOTH"