modLoader = "javafml"
loaderVersion = "${neoforge_version_range}"
license = "${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL = "https://updates.blamejared.com/get?n=${mod_id}&gv=${minecraft_version}&ml=neoforge"
displayURL = "${mod_homepage}"
credits = "This project is made possible with Patreon support from players like you. Thank you! ${mod_supporters}"
authors = "${mod_author}"
description = '''
${mod_description}
'''

[[dependencies.${ mod_id }]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "bookshelf"
mandatory = true
versionRange = "[21.0.14,)"
ordering = "NONE"
side = "BOTH"